- name: Restart the Prometheus service
  service:
    name: prometheus
    state: restarted
  listen: event_restart_prometheus
  become: true

- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload
  become: true