---
- hosts: prometheus
  become: yes
  become_method: sudo
  tags:
    - prometheus
  roles:
    - prometheus_install
    - prometheus_configure

- hosts: consul_agent
  become: yes
  become_method: sudo
  tags:
    - grafana
  roles:
    - grafana_install
    - grafana_datasource
    - grafana_dashboard


- hosts: alertmanager
  become: yes
  become_method: sudo
  tags:
    - alertmanager
  roles:
    - alertingmanager
    
- hosts: prometheus
  become: yes
  become_method: sudo
  tags:
    - alertmanager
  roles:
    - prometheus_configure_alertmanager


- hosts: alerta
  become: false
  environment:
     DATABASE_URL: "mongodb://localhost:27017/monitoring"
     PATH: /venv/bin:{{ ansible_env.PATH }}
     AUTH_REQUIRED: True
     ADMIN_USERS: admin@alerta.io,devops@alerta.io
     ADMIN_KEY: demo-key
     DEBUG: 1
  tags:
    - install
    - alerta
  roles:
    - alerta_ubuntu
  

- hosts: prometheus
  become: false
  environment:
     DATABASE_URL: "mongodb://localhost:27017/monitoring"
     PATH: /venv/bin:{{ ansible_env.PATH }}
     AUTH_REQUIRED: True
     ADMIN_USERS: admin@alerta.io,devops@alerta.io
     ADMIN_KEY: demo-key
     DEBUG: 1
  tags:
    - configure
    - alerta
  roles:
    - prometheus_configure_alerta

