- name: config file
  template:
    src: prometheus.conf.j2
    dest: /etc/prometheus/prometheus.conf

# - name: alert config file
#   copy:
#     src: "{{ role_path }}/files/alertrules.yml"
#     dest: /etc/prometheus/alert.rules.yml

- name: Start prometheus service
  service:
    name: prometheus
    state: started
    enabled: yes
  become: true

- name: Check if prometheus is accessible
  uri:
    url: http://localhost:9090
    method: GET
    status_code: 200
